language: node_js

cache: npm

install:
 - make install
 - npm install codecov nyc -g

node_js:
 - '7'
 - '9'

script: 
 - make ghoti
 - nyc mocha

after_success:
 - codecov -f ./coverage/coverage-final.json
