/**
 * @overview generated by ghoti-cli
 * @fileoverview Production build Entry
 */

import * as React from 'react';
import * as ReactDOM from 'react-dom';
import Hello from './root/hello';

import './style/global.sass';

const initialData = JSON.parse(document.getElementById('initial-data').getAttribute('data-json'));

ReactDOM.hydrate(
    (<Hello {...initialData} />),
    document.getElementById('container'),
);
