const comments = [
    {
        name: 'normal'
        content: [
            '/**'
            ' * @overview generated by ghoti-cli'
            ' * @fileoverview ${|overview|}'
            ' */'
        ]
    }
    {
        name: 'sharp'
        content: [
            '# generated by ghoti-cli'
            '# ${|overview|}'
        ]
    }
]

export comments