const comments = (type) ->
    var re
    re = '/**\r\n'
    re += '* @overview generated by ghoti-cli\r\n'
    re += '* @fileoverview ' + type + ' import file\r\n'
    re += '* You should not edit this file by hand\r\n'
    re += '*/\r\n\r\n'
    re

export comments